@baseUrl= http://localhost:3333/api
@authToken= {{login.response.body.access_token }}


# @name test
GET {{baseUrl}}/hello
Content-Type:  application/json
 
###

# @name create_account
POST {{baseUrl}}/auth/register
Content-Type:  application/json

{
    "name":"João",
    "email":"joao@gmail.com.br",
    "password":"123456"
}

###

# @name login
POST {{baseUrl}}/auth/login
Content-Type:  application/json

{
    "email":"joao@gmail.com.br",
    "password":"123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type:  application/json

{
    "email":"joao@gmail.com.br",
    "password":"123456"
}
