@baseUrl= http://localhost:3333/api
@authToken= {{ login.response.body.access_token }}

@ongCategoryId = {{ create_ong_category.response.body.id }}

@ongId = {{ create_ong.response.body.id }}

# @name test
GET {{ baseUrl }}/hello
Content-Type:  application/json
 
###

# @name create_account
POST {{ baseUrl }}/auth/register
Content-Type:  application/json

{
    "name":"João",
    "email":"joao@gmail.com.br",
    "password":"123456",
    "bio": "Teste bio",
    "role":"USER"
}

###

# @name login
POST {{ baseUrl }}/auth/login
Content-Type:  application/json

{
    "email":"joao@gmail.com.br",
    "password":"123456"
}


###

# @name create_ong
POST {{ baseUrl }}/ongs
Content-Type:  application/json
Authorization: Bearer {{authToken}}

{
    "document": "12314124143",
    "pixKey": "124423123",
    "name": "Ong 123"
}

###

# @name create_ong_category
POST {{ baseUrl }}/ongs/categories
Content-Type:  application/json
Authorization: Bearer {{authToken}}

{
    "name":"Animais4",
    "slug":"animais4"
}


###

# @name get_ong
GET {{ baseUrl }}/ongs/{{ ongId }}
Content-Type:  application/json
Authorization: Bearer {{authToken}}
 


###

# @name create_post
POST {{ baseUrl }}/posts
Content-Type:  application/json
Authorization: Bearer {{authToken}}
 
{
    "description": "Post Teste",
    "imageUrl": "",
    "title": "Title"
}

###

# @name get_post
GET {{ baseUrl }}/posts/1
Content-Type:  application/json
Authorization: Bearer {{authToken}}
 


###

# @name create_fundraiser
POST {{ baseUrl }}/fundraisers
Content-Type:  application/json
Authorization: Bearer {{authToken}}
 
{
    "description": "Vaquinha 123 Teste",
    "title": "Title",
    "arrecadationUrl": "https://arrecadacao.br",
    "pixKey": "1234567"
}

###

# @name get_fundraiser
GET {{ baseUrl }}/fundraisers/1
Content-Type:  application/json
Authorization: Bearer {{authToken}}
 

###

# @name create_chat
POST {{ baseUrl }}/chats
Content-Type:  application/json
Authorization: Bearer {{authToken}}
 
{
  "initiatorId":"1",
  "recipientId":"2"
}

###


# @name create_chat_message
POST {{ baseUrl }}/chats/messages
Content-Type:  application/json
Authorization: Bearer {{authToken}}
 
{
  "chatId": "1",
  "senderId": "1",
  "receiverId": "2",
  "message": "Teste message"
}


###

# @name get_chat
GET {{ baseUrl }}/chats/1
Content-Type:  application/json
Authorization: Bearer {{authToken}}


###

# @name get_chat_message
GET {{ baseUrl }}/chats/messages/1
Content-Type:  application/json
Authorization: Bearer {{authToken}}

###

# @name get_chat_messages
GET {{ baseUrl }}/chats/1/messages
Content-Type:  application/json
Authorization: Bearer {{authToken}}