services:
  can-i-helpu-database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: can-i-helpu
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    restart: always

  can-i-helpu-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      - can-i-helpu-database
    restart: always

networks:
  app-network:
    driver: bridge
