services:
  postgres:
    container_name: can-i-helpu-database
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: can-i-helpu
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
